export const LanguagesList = [
  'Python',
  'Java',
  'JavaScript',
  'C++',
  'C#',
  'PHP',
  'Ruby',
  'Go',
  'Swift',
  'Rust',
  'Kotlin',
  'Scala',
  'TypeScript',
  'Perl',
  'Bash',
  'R',
  'Objective-C',
  'Dart',
  'Groovy',
  'Elixir',
];
export const domainList = [
  'RN 框架 (React Native)',
  'Flutter 框架 (Flutter)',
  '动画 (Animation)',
  '网络及协议 (Networking&Protocol)',
  '加解密 (Encryption)',
  '数据库 (Database)',
  '文件及解析 (Files&Parsing)',
  '多媒体 (Media)',
  '图片 (Image)',
  '图形 (Graphics)',
  '人工智能 (AI)',
  '工具 (Tools)',
  '数学及算法 (Math&Algorithm)',
  '架构及模式 (Architecture&Patterns)',
  '日志及调试 (Logging&Debugging)',
  '辅助实用 (Utility)',
];
